### ISSUE TITLE
Collections support

### ISSUE THREAD

**Issue by anatosun** [arsaboo/beets-plexsync#30]
First let me say this plugin is awesome work, and thanks a lot for this!

It would be great if we could also work with collections with this tool and import playlists as track collections.

**Comment by arsaboo** [comment]
I think it should not be too difficult. We just need another function similar to the `_plex_add_playlist_item` to work with collections. 

https://github.com/arsaboo/beets-plexsync/blob/5a20029af77662f50ab21032dee7a207e6b9bb95/beetsplug/plexsync.py#L545

I will check it out unless you beat me to it.

**Comment by arsaboo** [comment]
An even easier approach may be to just add another function to convert the playlist to a collection. What do you think?

**Comment by arsaboo** [comment]
Let me know if the new `plexplaylist2collection` function does the job for you. Feel free to reopen the issue or open a new issue if you would like to see anything else.

**Comment by anatosun** [comment]
Let me try this later. Thanks for the quick action!
