### ISSUE TITLE
Google Bard API Support

### ISSUE THREAD

**Issue by gbcox** [arsaboo/beets-plexsync#35]
Would be nice to have the option to use Google Bard to create playlists.  I've noticed from using both openai and bard that they give different results.

**Comment by arsaboo** [comment]
Bard does not have and open API (yet) for me to test things out. I can try adding support for importing JSON files (which can be updated using Bard or any other LLM).

**Comment by gbcox** [comment]
Thanks for the quick reply.  Yeah, the API is in beta mode.  No rush, whenever you have the time.  Just thought it would be interesting to see how the services compare.

**Comment by arsaboo** [comment]
Completed https://github.com/arsaboo/beets-plexsync/pull/38
