### ISSUE TITLE
Add configuration around what attributes to fetch from Plex

### ISSUE THREAD

**Issue by Kernald** [arsaboo/beets-plexsync#45]
While the set of attributes fetched from Plex seems to be a sane default, in practice I'd like to cherry-pick what I'm fetching (specifically, only the user rating). Is there a way to configure what attributes are fetched or not?

**Comment by arsaboo** [comment]
I'm not opposed to adding such configuration. However, given that there are only two other variables - skip and view counts - that may be excluded, I'm unsure of the value of the same. What else would you like to exclude?

**Comment by Kernald** [comment]
The README mentions:

> and it will obtain guid, ratingkey, userrating, skipcount, viewcount, lastviewedat, lastratedat, and plex_updated.

Now that you mention it, I guess `guid` and `plex_updated` (and maybe `lastratedat`) are internally used to speed things up?

**Comment by arsaboo** [comment]
Indeed, many of the additional fields are for identification or other features. For example, `plex_viewcount` and `plex_lastviewedat` are used to check the most played albums for the collage.

**Comment by arsaboo** [comment]
Closing this for now...please open another issue if anything else comes up.
