### ISSUE TITLE
Add ability to modify baseurl for OpenAI API in order to use Local LLMs

### ISSUE THREAD

**Issue by lasagnacrab** [arsaboo/beets-plexsync#49]
I was hoping to be able to use this plugin in order to use my own locally hosted llm's for playlist creation instead of having to pay for OpenAI's API usage. 

Would be awesome if could plug in my own OpenAI compatible API server to keep everything local. I've been able to do this with other tools that allow you to modify the API URL, so I assume that could work here too.

**Comment by arsaboo** [comment]
I will get it it soon. PRs welcome
